### ISSUE TITLE
Version with Cats Effect

### ISSUE THREAD

**Issue by jdegoes** [zio/interop-cats#1]
I think we should version this library with Cats Effect.

e.g. if you're using Cats Effect 1.0, then you pull in `interop-cats` 1.0.

We can use the micro version for backward-compatible updates within a Cats Effect version.

Thoughts?

**Comment by GodPlaysChess** [comment]
I think it is convenient, though it means that we need to
1. release a new version every time cats-effect releasing a new version (even if we do not do any changes).
2. release a new subversion of it for any new zio-core release, even if the changes are major and cats-effect stays the same.

**Comment by mijicd** [comment]
As agreed in `ZIO/Core` gitter, we'll proceed with `vA.B.C.D` versioning scheme, `A.B.C` coming representing semantic version of a library, and `D` enumerating the patch made in interop.
