### ISSUE TITLE
Ambigous implicit values for `Sync`

### ISSUE THREAD

**Issue by Fristi** [zio/interop-cats#122]
While using http4s, the `EntityEncoder` has a constraint on `F[_] : Sync` when you import `zio.interop.catz._` you will get this while compiling:

```
ambiguous implicit values:
  both method syncZManagedInstances in trait CatsEffectZManagedInstances of type [R]=> cats.effect.Sync[[γ$13$]zio.ZManaged[R,Throwable,γ$13$]]
  and method taskConcurrentInstance in trait CatsEffectInstances1 of type [R]=> cats.effect.Concurrent[[β$18$]zio.ZIO[R,Throwable,β$18$]]
  match expected type cats.effect.Sync[F]
```

This is with RC10

**Comment by ghostdogpr** [comment]
Is it maybe same as #118? (need to pass type param explicitly)

**Comment by Fristi** [comment]
Confirmed, type param will fix it :)

I am thinking how this could be more user friendly in terms of interop use.. Guess until Scala 3.x this will be confusing right?

**Comment by ghostdogpr** [comment]
@neko-kai @mschuwalow what do you think? Should we separate instances and require different imports for `ZManaged`?

**Comment by Fristi** [comment]
That would help, I'm currently using `cats.effect.Resource` as it's common in http4s/doobie and lot's of code date back before `ZManaged` :)

**Comment by neko-kai** [comment]
@ghostdogpr 
Eh, that would probably need a `zmanaged.core` object as well. How about we put ZManaged instances into a lower priority? e.g.

```scala
import cats.effect.{Concurrent, Sync}
import zio.{ZIO, ZManaged}

object tst extends App {
  object catz extends catz1 {
    implicit def taskConcurrentInstance[R]: Concurrent[ZIO[R, Throwable, ?]] =
      _root_.zio.interop.catz.taskConcurrentInstance[R]
  }
  trait catz1 {
    implicit def syncZManagedInstances[R]: Sync[ZManaged[R, Throwable, ?]] =
      _root_.zio.interop.catz.syncZManagedInstances[R]
  }
  import catz._

  def getSync[F[_]: Sync] = Sync[F]
  val res                 = getSync
  assert(res.getClass eq taskConcurrentInstance.getClass)
}

```

**Comment by ghostdogpr** [comment]
@neko-kai sounds good, makes sense to get the instance for ZIO by default and to have to explicit otherwise.

**Comment by Fristi** [comment]
No longer an issue for me
