### ISSUE TITLE
Error combinaison when using parXXX in cats

### ISSUE THREAD

**Issue by larousso** [zio/interop-cats#139]
Hi, 

It could be good when the error side is a semigroup, that we could do 

```scala
val io1: IO[NonEmptyList[String], Unit] = IO.fail(NonEmptyList.of("Error 1"))
val io2: IO[NonEmptyList[String], Unit] = IO.fail(NonEmptyList.of("Error 2"))

val io3: IO[NonEmptyList[String], (Unit, Unit)] = (io1, io2).parTupled
// IO.fail(NonEmptyList.of("Error 1", "Error 2"))
```

This works in cats with eithers but not with zio at the moment. I would be happy to contribute on this one but I'm not sure to understand the code that is done in `cats` for the `Parallel` instance for `Either`.

**Comment by neko-kai** [comment]
@larousso The errors are already accumulated in `Cause[E]` for ZIO. Could you please check if `(io1, io2).parTupled.mapErrorCause(_.failures.toNel.get.flatten)` contains all the errors you're looking for?

**Comment by larousso** [comment]
Yes, this is working : 

```scala 
testM("zio") {
  import cats.implicits._
  import zio.interop.catz._
  assertM(
    (ZIO.fail("Error1"), ZIO.fail("Error2")).parTupled.mapErrorCause { c =>
      Cause.fail(NonEmptyList.fromListUnsafe(c.failures))
    }.either,
    isLeft(
      equalTo(NonEmptyList.of("Error1", "Error2"))
    )
  )
}
```

**Comment by neko-kai** [comment]
@larousso In that case I think this issue can be closed? I feel like there wouldn't be much gain from a new `Parallel` instance with `E: Semigroup` constraint since `Cause` already does the accumulation here....

**Comment by larousso** [comment]
I really prefer the concise syntax with just 
```scala
(io1, io2).parTupled
``` 
instead of 
```scala
(io1, io2).parTupled.mapErrorCause { 
  c => Cause.fail(NonEmptyList.fromListUnsafe(c.failures).reduce)
}
``` 
but I understand that it's not fine for you to add a new instance with a E as a monoid so I can close the issue.

**Comment by neko-kai** [comment]
@larousso you _can_ add it and there's a precedent with MonoidK/SemigroupK instances - https://github.com/zio/interop-cats/blob/master/interop-cats/shared/src/main/scala/zio/interop/cats.scala#L109 - but then I'm not sure how intuitive it would be to change the error behavior based on existence/nonexistence of instances for error (the same applies to the SemigroupK instance)

**Comment by larousso** [comment]
It seams to be the standard behavior for cats. 
For exemple:

```scala 
        testM("cats") {
          import cats._
          import cats.data._
          import cats.implicits._
          import zio.interop.catz._

          val et1 = EitherT.leftT[Task, String](NonEmptyList.one("Error1"))
          val et2 = EitherT.leftT[Task, String](NonEmptyList.one("Error2"))

          assertM(
            (et1, et2).parTupled.value,
            isLeft(
              equalTo(NonEmptyList.of("Error1", "Error2"))
            )
          )
        }
```

**Comment by neko-kai** [comment]
@larousso The difference is that you must specifically wrap your IO in `EitherT` to enable this behavior. There's no low-priority instance for Parallel[EitherT[...]] that **doesn't** require a Semigroup instance – therefore your errors will either be accumulated or your compilation will fail, there won't be a **silent** change of behavior towards non-accumulation from a missing instance.

**Comment by neko-kai** [comment]
For ZIO there's a silent change of behavior in `SemigroupK` currently. I'm not super fond of that as is, with a conditional `Parallel` instance there will be more silent changes of behavior...

/cc @zio/core  for opinions...

**Comment by jdegoes** [comment]
ZIO cannot guarantee parallel error accumulation. This is because when one running effect fails, the others are canceled immediately... possibly before they begin.

You could do:

```scala
ZIO.uninterruptible {
  ...
}
```

If you wanted to "force" non-cancellation. That should allow you to get parallel error accumulation.
