### ISSUE TITLE
BuildInfo class collides with BuildInfo from ZIO

### ISSUE THREAD

**Issue by mlangc** [zio/interop-cats#16]
This causes problems for example when generating assemblies:
```
[error] 1 error was encountered during merge
[error] java.lang.RuntimeException: deduplicate: different file contents found in the following:
[error] /Users/mlanger/.ivy2/cache/dev.zio/zio-interop-cats_2.12/jars/zio-interop-cats_2.12-1.3.1.0-RC3.jar:zio/BuildInfo$.class
[error] /Users/mlanger/.ivy2/cache/dev.zio/zio_2.12/jars/zio_2.12-1.0.0-RC10-1.jar:zio/BuildInfo$.class
```

This issue can be fixed easily by adapting the following line:
https://github.com/zio/interop-cats/blob/a8cb061d4dfaaba2fb1a665a1f6c44f9503ce4fe/project/ScalazBuild.scala#L36

**Comment by kaishh** [comment]
Do you use the generated BuildInfo? Maybe we could just stop generating it?

**Comment by mlangc** [comment]
I didn't even know that it exists before getting the collision during assembly generation, so for me dropping it would be fine. However, I personally like the idea of having convenient programmatic access to build related metadata, and since `ZIO` core provides it too (as well as some other popular libraries like `shapeless` and `refined`), I would just adapt the package. If it doesn't help, it won't hurt - at least in my opinion.

**Comment by kaishh** [comment]
Hmm, my reservation is caused by that I don't want a new package to interfere with autocompletion when writing `import zio.interop.catz._`... How about a package like `zio.build.interop.catz` ?
@mijicd @ghostdogpr

**Comment by mijicd** [comment]
Yeah, I've added build info during the interop migration. Thus being said, I'd rather drop it than invent new packages.
