### ISSUE TITLE
Resource toManaged throws with RC14

### ISSUE THREAD

**Issue by Fristi** [zio/interop-cats#182]
For me with zio RC19-1 and interop-cats RC14 and fs2-kafka 1.0.0 it throws at runtime an exception when I call `Resource.toManaged`

```
[info]     java.lang.NoSuchMethodError: 'cats.effect.Resource cats.effect.Resource.mapK(cats.arrow.FunctionK, cats.Defer, cats.Applicative)'
[info]     	at zio.interop.CatsIOResourceSyntax$.toManaged$extension(catszmanaged.scala:77)
```

**Comment by neko-kai** [comment]
@Fristi Could you try updating `cats-effect` to `2.1.3` or higher? This should fix the issue.

**Comment by Fristi** [comment]
That resolved the issue! Thank you very much
