### ISSUE TITLE
Bug: zio.Reservation cannot be cast to scala.Tuple2

### ISSUE THREAD

**Issue by kolov** [zio/interop-cats#188]
This code:
``` 
   val Live: ZLayer[zio.ZEnv, Throwable, GSuiteSaml] = ZLayer.fromEffect {
    ZIO.runtime[Any] map { implicit rts =>
      val client: ZManaged[Any, Throwable, Client[Task]] =
        BlazeClientBuilder[Task](rts.platform.executor.asEC).resource.toManagedZIO
      new Service {
        override def submitRequest(uri: Uri, samlRequest: String): Task[String] = {
          client.use { c =>
  ```
produces the stack trace below. If I drop `.toManagedZIO` and use the cats effects `Resource`, all works.

╠─An unchecked error was produced.
║ java.lang.ClassCastException: zio.Reservation cannot be cast to scala.Tuple2
║ 	at zio.internal.FiberContext.evaluateNow(FiberContext.scala:844)
║ 	at zio.internal.FiberContext.$anonfun$fork$3(FiberContext.scala:706)
║ 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
║ 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
║ 	at java.lang.Thread.run(Thread.java:748)
║ 
║ Fiber:Id(1591194341124,11) was supposed to continue to:
║   a future continuation at zio.ZIO.run(ZIO.scala:1537)
║   a future continuation at zio.ZIO.bracket_(ZIO.scala:254)
║   a future continuation at zio.ZManaged.use(ZManaged.scala:994)
║   a future continuation at zio.ZIO.run(ZIO.scala:1537)
║   a future continuation at zio.ZManaged.use(ZManaged.scala:993)
║   a future continuation at zio.ZIO.bimap(ZIO.scala:223)
║   a future continuation at xxx.loginLogic(AuthRoute.scala:116)
║   a future continuation at xxx.AuthRoute.loginLogic(AuthRoute.scala:123)

**Comment by adamgfraser** [comment]
Are you sure you don't have an incompatible dependency somewhere? It sounds to me like an issue of having one dependency with the more recent `ZManaged` encoding and one with the older one.

**Comment by kolov** [comment]
I have zio  "1.0.0-RC20", zio-Interop-cats  "2.1.3.0-RC15". I'll try to resolve all evicted dependencies.

**Comment by debasishg** [comment]
I got this exception with zio "1.0.0-RC20", zio-Interop-cats "2.0.0.0-RC12" and using doobie "0.8.8". Moving to zio-Interop-cats "2.1.3.0-RC15" fixed the issue.

**Comment by ghostdogpr** [comment]
I think this was due to incompatible versions and can be closed now, but feel free to reopen if it still happens.
