### ISSUE TITLE
Cats Effect: Queue

### ISSUE THREAD

**Issue by jdegoes** [zio/interop-cats#22]
Introduce an effect-polymorphic class atop `ZQueue`, with a default implementation for any Cats Effect data type (Cats IO, Monix Task, etc.).

```scala
package scalaz.zio.interop

trait Queue[F[_], +A] {
  ...
}
object Queue {
  ...
}
```

The methods will all delegate to ZIO `ZQueue`, but they will take the `ZIO` effect returned by `ZQueue` methods and lift it into any effect `F[_]` that is suitable equipped.

**Comment by calvinlfer** [comment]
It’s been quite a while on this one. @adamgfraser helped me make a lot of progress so I’d like to continue working on this if that’s alright

**Comment by calvinlfer** [comment]
Completed by https://github.com/zio/interop-cats/pull/146
