### ISSUE TITLE
Ambiguous implicits for cats.effect.Effect[UIO]

### ISSUE THREAD

**Issue by cornerman** [zio/interop-cats#227]
Using cats interop with `zio.Task` works perfectly, but I cannot get a `cats.effect.Effect` for `zio.UIO` - which afaik should work as well.

Given the following example:
```scala
import zio._
import zio.interop.catz._

implicit def r = zio.Runtime.default
val F: cats.effect.Effect[Task] = implicitly // compiles
val FX: cats.effect.Effect[UIO] = implicitly // error
```

For the latter one, I get a compile error:
```
[error] ambiguous implicit values:
[error]  both method $conforms in object Predef of type [A]=> A => A
[error]  and method zioContextShift in class CatsEffectInstances of type [R, E]=> cats.effect.ContextShift[[γ$6$]zio.ZIO[R,E,γ$6$]]
[error]  match expected type T
[error]   val FX: cats.effect.Effect[UIO] = implicitly
[error]                                     ^
[info] Unit <: cats.effect.Effect[zio.UIO]?
[info] false
```

Any ideas?

**Comment by joroKr21** [comment]
Why should it work? `Effect` extends `MonadError` of `Throwable`.

**Comment by cornerman** [comment]
> Why should it work?

Because `UIO` is a subtype of `Task` (like `ZIO[Any, Nothing, T] < ZIO[Any, Throwable, T]`). It is unfailable, but that does not mean, it cannot fulfill the `MonadError` with `Throwable`. It already works, if you explicitly add a type ascription, like `needsEffect(UIO.succeed(1))` fails but `needsEffect(UIO.succeed(1): Task[Int])` works.

**Comment by joroKr21** [comment]
But we cannot implement `def raiseError[A](error: Throwable): UIO[A]`

**Comment by cornerman** [comment]
Good point, you are right!
