### ISSUE TITLE
Intermittent failure in toIO stack safety

### ISSUE THREAD

**Issue by jdegoes** [zio/interop-cats#25]
```
ConcurrentEffect[Task].concurrentEffect.toIO stack safety *** FAILED ***
```

**Comment by joroKr21** [comment]
> That looks like the failure. Cats has a strange notion of "equality" and diagnosing these issues is a real pain.

I think the problem is that the `TestContext` is not propagated correctly. See #28

**Comment by neko-kai** [comment]
Seems like the build is stable these days
