### ISSUE TITLE
Scala3

### ISSUE THREAD

**Issue by cheriot** [zio/interop-cats#283]
I'm trying to use the Zio ecosystem with scala3 and running into this situation:

* Zio built for scala 2.13 doesn't work with scala 3
* A project using Zio built for scala 3 that has transitive dependencies on Zio for 2.13 (via zio-interop-cats for 2.13) will get "Modules were resolved with conflicting cross-version suffixes" errors

Is there a workaround or a prerelease that can work with scala3?

**Comment by catostrophe** [comment]
Try to use `zio-interop-cats` in `withDottyCompat` mode and exclude all the transitive dependencies with `.exclude`

**Comment by neko-kai** [comment]
Closed by #287
