### ISSUE TITLE
Scala 3.0.0-RC1 compatibility (ZIO 1.0.5)

### ISSUE THREAD

**Issue by adamsar** [zio/interop-cats#310]
With zio 1.0.5 just released with RC1 compatibility, building with the latest version of interop-cats gives conflicting cross-version errors. ZIO is unusable in when using `dottyCompat` dependency resolution, so there's no way to use interop-cats currently.

**Comment by adamgfraser** [comment]
There is an existing PR #309 to add support for `3.0.0-RC1` that I expect will be merged shortly. Until then you can use previous ZIO versions with earlier Scala 3 version. Until a stable version of Scala 3 is released I'm afraid this is the boat we are all in. All libraries are trying to upgrade as soon as their dependencies allow and are generally doing so quite quickly but when everyone has to move in lock step it is going to take a little time.
