### ISSUE TITLE
Interop with skunk may die instead catch error

### ISSUE THREAD

**Issue by tolikbotov** [zio/interop-cats#343]
I use zio-interop-cats with [skunk](https://github.com/tpolecat/skunk).

There is serializable transaction error occurs in postgres. I expect that catchAll should catch exception, but all application fails.

When usung cats.effect all errors are catched as expected.

This code is workaround, without it i cannot catch this error:
```
.sandbox
.catchAll { cause =>
  cause.defects.collectFirst {
    case e: PostgresErrorException =>
      if (e.code == "40001") ZIO.fail(new IllegalStateException("Serialization error occurs"))
      else ZIO.fail(e)
  }
    .getOrElse(
      ZIO.halt(cause)
    )
}
```

Please point me on how i can fix this.

Related issue in skunk's github is https://github.com/tpolecat/skunk/issues/438

[test-skunk.zip](https://github.com/zio/interop-cats/files/6382677/test-skunk.zip)

Version of zio-interop-cats should be 2.3.1.0 in example.

**Comment by adamgfraser** [comment]
@tolikbotov Thanks for reporting! It looks like Skunk is improperly throwing an error that is not suspended in an effect constructor and relying on undefined behavior in Cats Effect to catch that error. The best solution would be for Skunk to fix this but it does not look like that is going to happen. 😃

You can use the  `unrefine` operator to convert some fiber failures into errors:

```scala
effect.unrefine {
  case e: PostgresErrorException if e.code == "40001" =>
    new IllegalStateException("Serialization error occurs")
}
```

**Comment by tolikbotov** [comment]
Thank you.
