### ISSUE TITLE
Consider Providing Cats Core Instances More Directly

### ISSUE THREAD

**Issue by adamgfraser** [zio/interop-cats#366]
Right now if you want to get Cats instances for some ZIO data types you need to do `import zio.interop.catz.core._` instead of `import zio.interop.catz._`. For example the `Traverse` instance for `Chunk` is not in scope without that import. Should we have `catz` directly extend these instances so the user can get everything they need in one import? Otherwise I worry it can be somewhat confusing for the user, especially since some Cats instances such as `Monad` for `UIO` are in scope without doing this because they are implemented by Cats Effect instances.

@neko-kai @ghostdogpr What do you think?

**Comment by neko-kai** [comment]
This is definitely a bug - `core` is supposed to have a strict subset of instances from `catz`.
