### ISSUE TITLE
ZIO 2.0: Tagless-Final Tracing

### ISSUE THREAD

**Issue by adamgfraser** [zio/interop-cats#426]
We can support tracing for programs using ZIO 2.0 with Cats Effect code by capturing the tracing information for every operation in `zio-interop-cats` using the Akka line number tracer from ZIO 1.0 and using it to create a `ZTraceElement`.

Steps to do this:

- [ ] Copy the Akka line number tracer implementation from ZIO 1.0 [here](https://github.com/zio/zio/blob/master/stacktracer/jvm/src/main/scala/zio/internal/stacktracer/impl/AkkaLineNumbersTracer.scala) into `zio-interop-catz`
- [ ] Update every operator defined in `cats-effect` to capture the tracing information using the Akka line number tracer.
- [ ] Use that tracing information to generate a `ZTraceElement`
- [ ] Feed that `ZTraceElement` to satisfy the implicit trace expected by the ZIO operator
- [ ] Activate `disableAutoTracing` in all files to verify that we are always propagating tracing information we have generated

**Comment by jdegoes** [comment]
A few more notes:

1. Capture the source information from the `.getClass` of the lambda passed into the operation. For example, when implementing `bind`, you are passed a continuation `f: A => F[B]`, you should generate tracing based on `f.getClass`.
2. To make this more performant, we must cache the `Class[_] => ZSourceElement` relationship in a `ConcurrentMap[Class[_], ZSourceElement]`.
