### ISSUE TITLE
Scala.js artifact missing

### ISSUE THREAD

**Issue by durban** [zio/interop-cats#471]
The `dev.zio:zio-interop-cats_sjs1_3:3.2.9.0` artifact seem to be missing from maven central. For reference, sbt tries to download this: https://repo1.maven.org/maven2/dev/zio/zio-interop-cats_sjs1_3/3.2.9.0/zio-interop-cats_sjs1_3-3.2.9.0.pom. The setting I've used is `"dev.zio" %%% "zio-interop-cats" % "3.2.9.0"`. The JVM artifact seems to exist.

(See also #462, although I've no idea if it's related.)

**Comment by neko-kai** [comment]
Recent versions are currently published for Scala 3+Scala.js https://search.maven.org/artifact/dev.zio/zio-interop-cats_sjs1_3
