### ISSUE TITLE
MonadCancel instance is unlawful

### ISSUE THREAD

**Issue by neko-kai** [zio/interop-cats#503]
The behavior of `MonadCancel#canceled` method doesn't seem to map to `ZIO.interrupt` at all. In particular the following law:
```scala
  def uncancelableCanceledAssociatesRightOverFlatMapAttempt[A](fa: F[A]) =
    (F.uncancelable(_ => F.canceled >> fa).attempt >> F.unit) <->
      F.forceR(F.uncancelable(_ => fa))(F.canceled)
```
and the associated comment:
```
   * In the following example, the fiber requests self-cancelation in a masked
   * region, so cancelation is suppressed until the fiber is completely
   * unmasked. `fa` will run but `fb` will not.
   *
   * {{{
   *
   *   F.uncancelable { _ =>
   *     F.canceled *> fa
   *   } *> fb
   *
   * }}}
```

This appears to mean that:

1. `canceled` is ignored in uninterruptible regions
2. However, when uncancelable region is over, `canceled` will execute immediately (hence 'associates right')

That behaves just like external interruption - but sent from yourself to yourself, not the immediate internal interruption of `ZIO.interrupt`.
Implementing that directly would require calling `interruptAs` on the `FiberContext` of the current fiber, which I'm not sure is doable without modifying the runtime.

Note: tests did not catch that since Eq instance for IO in tests only compares output Cause, not executed effects – which would be `Cause.Interrupted` on both sides of the equation, but the `fa` effect will only run on the right hand side.

/cc @adamgfraser @joroKr21

**Comment by joroKr21** [comment]
Let me play devil's advocate - does that matter in practice?

**Comment by neko-kai** [comment]
@joroKr21 Only matters if anyone uses this behavior in a library somewhere. Considering that the example of it is shown right in the middle of `cancel`'s scaladoc, it's quite likely to happen eventually. 😫

**Comment by neko-kai** [comment]
Actually, I believe this law was supposed to catch it:
```scala
  def uncancelableCanceledAssociatesRightOverFlatMapAttempt[A](fa: F[A]) =
    (F.uncancelable(_ => F.canceled >> fa).attempt >> F.unit) <->
      F.forceR(F.uncancelable(_ => fa))(F.canceled)
```
It doesn't fail due to the Arbitrary instance – when Arbitrary instance is replaced with a conversion from cats-effect it does fail then:

```scala
  implicit def arbTask[A: Arbitrary: Cogen](implicit ticker: Ticker): Arbitrary[Task[A]] = Arbitrary {
    arbitraryIO[A].arbitrary.map(liftIO(_))
  }

  def liftIO[A](io: cats.effect.IO[A])(implicit ticker: Ticker): zio.Task[A] =
    ZIO.effectAsyncInterrupt {
      k =>
        val (result, cancel) = io.unsafeToFutureCancelable()
        k(ZIO.fromFuture(_ => result))
        Left(ZIO.fromFuture(_ => cancel()).orDie)
    }
```

**Comment by joroKr21** [comment]
Oh yes, I keep forgetting that the `Arbitrary` instance we have here is not exhaustive at all.
I was trying to figure out a test to show that it fails but your idea of converting from `IO` sounds pretty good.

**Comment by neko-kai** [comment]
After https://github.com/zio/interop-cats/pull/544 `ZIO.interrupt` won't even trigger `MonadCancel#onCancel` since it would now be `Outcome.Errored`, not `Outcome.Canceled` - the latter being reserved only for external interruption. The intended semantic of sending an external interruption to the current fiber would have to be implemented for `cancel` to make any sense.

**Comment by joroKr21** [comment]
Wow very nice findings - tricky stuff 👍
