### ISSUE TITLE
Support ZIO Test

### ISSUE THREAD

**Issue by jdegoes** [zio/interop-cats#51]
We should have a `test` package you can import that will let you run arbitrary `F[_]` tests for any effect monad, by tying in ZIO interruption to `F[_]` interruption, asynchronous conversion.

 - [ ] `testF`
 - [ ] `checkF`
 - [ ] `checkSomeF`
 - [ ] `checkAllF`

Any others?

**Comment by adamgfraser** [comment]
I can work on this. So the type signature of `testF` for example would be:

```scala
final def testF[L, F[_]: ConcurrentEffect](label: L)(assertion: F[TestResult]): ZSpec[Any, Throwable, L, Unit]
```

And the use case would be a user should be able to write tests using `testF` and other combinators in a Spec like `DefaultRunnableSpec` and they should "just work", is that right?
