### ISSUE TITLE
Streams hang when converting fs2 -> zio -> fs2 + map

### ISSUE THREAD

**Issue by adamw** [zio/interop-cats#533]
We're debugging hanging websocket tests as part of https://github.com/softwaremill/tapir/pull/2043 (things work fine w/ zio1, stop working when updating to the latest RCs of zio2).

I think I minimised the problem to the following:

```scala
import zio.Task
import zio.stream.interop.fs2z._
import zio.interop.catz._

import scala.concurrent.duration.DurationInt

object Test extends App {
  val input: fs2.Stream[Task, String] = fs2.Stream[Task, String]("abc") ++
    fs2.Stream.awakeEvery[Task](1.second).map { _ =>
      println("PRODUCING"); "xyz"
    }

  zio.Runtime.global.unsafeRunToFuture(input.toZStream().toFs2Stream.map(x => x).compile.drain)
}
```

When this is run, nothing gets printed to the console. Removing `.toZStream().toFs2Stream` or, interestingly, `.map(x => x)`, causes `PRODUCING` to be printed out in the expected intervals.

**Comment by adamw** [comment]
Hm what's `zio2-interop-ce3`? :) I'm using `"dev.zio" %% "zio-interop-cats" % "3.3.0-RC5"`

**Comment by adamw** [comment]
(my suspicion being that things stop working when using latest fs2/cats-effect :) )

**Comment by adamgfraser** [comment]
Aren't these versions supposed to be binary compatible?

**Comment by adamgfraser** [comment]
Looks like this was broken in `fs2` version `3.1.1`.

**Comment by gavares** [comment]
Is this a bug in `fs2` or a bug in this library?

**Comment by adamw** [comment]
@adamgfraser Works, thanks a lot for the fix & fast release! :)

**Comment by adamgfraser** [comment]
@adamw Awesome! 😃
