### ISSUE TITLE
Canceler unlawfully ignored in CE3 `Async#async` implementation, can cause hangs etc.

### ISSUE THREAD

**Issue by neko-kai** [zio/interop-cats#541]
In implementation of `async`, the result of `k` is ignored https://github.com/zio/interop-cats/blob/zio2-interop-ce3/zio-interop-cats/jvm/src/main/scala/zio/interop/ZioAsync.scala#L43= :
```
        k(either => register(promise.await *> ZIO.fromEither(either))) *> promise.succeed(())
```

Going by scaladocs, `k`'s return value is significant:

```
`k` returns an `Option[F[Unit]]` which is an optional finalizer to be run in the event that
the fiber running {{{async(k)}}} is canceled.
```

That is, seems like the the return of `k` ought to be stuffed into `.onInterrupt` and ignoring the finalizer could hang the program if it relies on the finalizer for synchronization in event of interruption for the async, as the description says it should. (Odd that discipline tests missed that)

/cc @joroKr21 @adamgfraser

**Comment by joroKr21** [comment]
Cancellation is tricky to test in laws. I guess we could use `ZIO.scoped` - WDYT? But for ZIO 1 it sounds like we need `asyncInterruptZIO` which doesn't exist.

**Comment by neko-kai** [comment]
@joroKr21 
I wrote the following for 1.0, can't be sure it works, but I think using `.onInterrupt` should be enough to replicate the semantic, probably:
```scala

def async[A](k: (Either[Throwable, A] => Unit) => IO[Throwable, Option[IO[Throwable, Unit]]]): IO[Throwable, A] = {
  for {
    cancelerPromise <- Promise.make[Nothing, Option[IO[Throwable, Unit]]]
    res <- IO
      .effectAsyncM[Throwable, A] {
        resume =>
          k(exitEither => resume(IO.fromEither(exitEither)))
            .onExit {
              case zio.Exit.Success(maybeCanceler) => cancelerPromise.succeed(maybeCanceler)
              case _: zio.Exit.Failure[?] => cancelerPromise.succeed(None)
            }
      }.onInterrupt(
        cancelerPromise.await.flatMap(IO.foreach(_)(identity)).orDie
      )
  } yield res
}

```

**Comment by Lermex** [comment]
@neko-kai just to clarify, is this a new thing (circa ZIO 2.0) or has it been like that for a long time? I'm asking because we've had some fiber hanging problems for a long time and we're also seeing an increase in them after having migrated to zio 2, but I think these two things may be unrelated.

**Comment by neko-kai** [comment]
@Lermex This is new since Cats-Effect 3, on both ZIO 1 & 2
