### ISSUE TITLE
CE and fs2 versions are out of date

### ISSUE THREAD

**Issue by davesmith00000** [zio/interop-cats#596]
I'm attempting to get my frontend lib working with ZIO, and ran into the following:

```
[error] (tyrianZIO / update) found version conflict(s) in library dependencies; some are suspected to be binary incompatible:
[error] 
[error]         * co.fs2:fs2-core_sjs1_3:3.2.11 (early-semver) is selected over 2.5.6
[error]             +- io.indigoengine:tyrian_sjs1_3:0.5.2-SNAPSHOT       (depends on 3.2.11)
[error]             +- dev.zio:zio-interop-cats_sjs1_3:22.0.0.0           (depends on 2.5.6)
[error] 
[error]         * org.typelevel:cats-effect_sjs1_3:3.3.14 (early-semver) is selected over 2.5.1
[error]             +- io.indigoengine:tyrian-zio_sjs1_3:0.5.2-SNAPSHOT   (depends on 3.3.14)
[error]             +- co.fs2:fs2-core_sjs1_3:3.2.11                      (depends on 3.3.14)
[error]             +- dev.zio:zio-interop-cats_sjs1_3:22.0.0.0           (depends on 2.5.1)
```

It appears that the code base is now depending on a more modern version (?), any sense of how far off an update might be?

**Comment by neko-kai** [comment]
@davesmith00000 You need to use version `3.3.0` for CE3

**Comment by davesmith00000** [comment]
Hi @neko-kai,

Thank you, I was clearly on the wrong track there! :smile: 

However I still don't think the artefacts are published? Am I doing something wrong?

```
[warn]  Note: Unresolved dependencies path:
[error] stack trace is suppressed; run last tyrianZIO / update for the full output
[error] (tyrianZIO / update) sbt.librarymanagement.ResolveException: Error downloading dev.zio:zio-interop-cats_sjs1_3:3.3.0
[error]   Not found
[error]   Not found
[error]   not found: /home/dave/.ivy2/local/dev.zio/zio-interop-cats_sjs1_3/3.3.0/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/dev/zio/zio-interop-cats_sjs1_3/3.3.0/zio-interop-cats_sjs1_3-3.3.0.pom
[error]   not found: https://s01.oss.sonatype.org/content/repositories/snapshots/dev/zio/zio-interop-cats_sjs1_3/3.3.0/zio-interop-cats_sjs1_3-3.3.0.pom
```

![image](https://user-images.githubusercontent.com/908709/184976480-01b61ad5-2bf9-49d3-9318-39b93fa5c1b6.png)

**Comment by neko-kai** [comment]
@davesmith00000 This version is not published for Scala.js on Scala 3 (https://search.maven.org/artifact/dev.zio/zio-interop-cats_sjs1_3)
You may need to submit a PR to fix this (like recent #600)

**Comment by davesmith00000** [comment]
Here you go @neko-kai:
https://github.com/zio/interop-cats/pull/603

**Comment by davesmith00000** [comment]
Merged and included in the current SNAPSHOT release `3.3.0+9-bd953aa9-SNAPSHOT`. Appears to work just fine.

**Comment by davesmith00000** [comment]
Hi @adamgfraser - I'm a bit muddled on the versioning scheme but I'm guessing this hasn't made it into an official release yet? No pressure, I'm going to do a Tyrian release later (all being well) and thought I'd upgrade if the option was available.

**Comment by adamgfraser** [comment]
@davesmith00000 Just released a new version.

**Comment by davesmith00000** [comment]
Excellent - thank you kindly!
