### ISSUE TITLE
Dependency on `zio.clock` package

### ISSUE THREAD

**Issue by amricko0b** [zio/interop-cats#636]
Hello everyone!

I've found a very surprising behavior using `zio-interop-cats`.

When I try to compile my code, I observe the following error:
```
Symbol 'term zio.clock.package' is missing from the classpath.
[error] This symbol is required by 'value zio.interop.CatsEffectInstances.runtime'.
[error] Make sure that term package is in your classpath and check for conflicting dependencies with `-Ylog-classpath`.
[error] A full rebuild may help if 'CatsEffectInstances.class' was compiled against an incompatible version of zio.clock.
```

And it seems to be fair, 'cause (as far as I know) there is no `clock` package in zio 2.x. Looks like some kind of compatibility issue...

Could you please help me and provide some explanation on this error? Still, there could be something I did wrong...

I use:
zio: `2.0.1`
zio-interop-cats: `13.0.0.1`
cats-effect: `3.3.14`

**Comment by adamgfraser** [comment]
`13.0.0.1` contains support between ZIO 1 and Cats Effect 3 but you are using ZIO 2. You want `3.3.0`.

**Comment by amricko0b** [comment]
Hello, @adamgfraser!

Thank you for your help! After changing version to `3.3.0` the issue had gone.
I wrongly assumed that "latest version supports latest version" =)
Next time I'l be more careful.

Closing this. Many thanks again!
