### ISSUE TITLE
Upgrade zio version to latest.

### ISSUE THREAD

**Issue by ujali** [zio/interop-cats#656]
The current interop-cats tag is not compatible with the latest `zio`. Therefore, when we upgrade zio version to the `latest` with the current version of `interop-cats` in our projects, It is causing some tests to fail due to the changed behavior. can we please upgrade it to the latest zio version?

**Comment by neko-kai** [comment]
Version [23.0.0.2](https://github.com/zio/interop-cats/tree/v23.0.0.2) is using zio version 2.0.6. Do you experience breakage when updating from zio 2.0.6 to zio 2.0.10?

**Comment by ujali** [comment]
Hi @neko-kai,
Sorry for the late reply. I updated the `zio version` to the latest(2.0.10) [here](https://github.com/zio/interop-cats/pull/657).

**Comment by neko-kai** [comment]
Fixed in #657
