### ISSUE TITLE
Graceful shutdown of http4s-ember-server with ZIO hanging

### ISSUE THREAD

**Issue by mleclercq** [zio/interop-cats#666]
When running a http4s ember server with ZIO interop, the shutdown of the server when sending a TERM signal to the process is hanging forever.

See example repo: https://github.com/mleclercq/http4s-ember-zio with a fiber dump. 

I double checked that a similar example with cats-effect IO works this is why I'm opening an issue here as I guess it is an issue with ZIO/cats interop

It's not clear to me where this is hanging, but I found several references to past problems with the graceful shutdown of ember server on http4s repo ([here](https://github.com/http4s/http4s/pull/4471#discussion_r578903323) and [here](https://github.com/http4s/http4s/issues/6978)) so it looks like it's a complicated subject just with CE...

**Comment by kyri-petrou** [comment]
@jdegoes Tried to reproduce the issue and it doesn't exist in versions `>= 2.0.0.5`. I think the issue can be closed
