### ISSUE TITLE
Add implicit fs2.io.net.Network instance 

### ISSUE THREAD

**Issue by sheunis** [zio/interop-cats#667]
I recent change in fs2 [here](https://github.com/typelevel/fs2/pull/3179) deprecated summoning an implicit Network instance for Async. As a result, any code like this: `EmberClientBuilder.default[Task].build`, where an Async instance for Task is available will break. We can get around this by using a wrapper function where the Async and Network type constraints are declared, but this feels dirty. It would be nicer if the cats interop libs could have an implicit Network instance for a Task that can be imported.

**Comment by neko-kai** [comment]
Fixed in https://github.com/zio/interop-cats/pull/668/
